Add shellcheck to ensure that format of files in /etc/default are valid

diff --git a/rpi-eeprom-update b/rpi-eeprom-update
--- a/rpi-eeprom-update
+++ b/rpi-eeprom-update
@@ -7,6 +7,7 @@ set -e
 script_dir=$(cd "$(dirname "$0")" && pwd)
 
 if [ -f /etc/default/rpi-eeprom-update ]; then
+   [ shellcheck -e SC2148,SC2034 "${CUSTOM_EEPROM_CONFIG}" ] || die "Invalid rpi-eeprom-update configuration at ${CUSTOM_EEPROM_CONFIG}"
    . /etc/default/rpi-eeprom-update
 fi
 
@@ -115,6 +116,8 @@ prepareImage()
 
       # Apply user customisations to new EEPROM config
       if [ -f "${CUSTOM_EEPROM_CONFIG}" ]; then
+         [ shellcheck -e SC2148,SC2034 "${CUSTOM_EEPROM_CONFIG}" ] || die "Invalid custom EEPROM configuration at ${CUSTOM_EEPROM_CONFIG}"
+
          while read line; do
             field="$(echo "${line}" | cut -d'=' -f1)"
 
